[project]
name = "PySide Widgets Project"

[tool.pyside6-project]
files = ["Dokter.py", "Jadwal.py", "Pasien.py", "Poliklinik.py", "crud_jadwal.py", "crud_pasien.py", "crud_poliklinik.py", "formDokter.ui", "formJadwal.ui", "formPasien.ui", "formPoliKlinik.ui", "main.py", "main.ui"]
